---
name: build
on:
  push:
    branches:
      - devops/*
    tags:
      - v*

env:
  CONTAINER_REGISTRY: eu.gcr.io
  CONTAINER_REPOSITORY: phrasal-faculty-363013/infra
  PROJECT_NAME: atlantis-custom

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@v1
        with:
          account_key: ${{ secrets.GCP_CREDENTIALS }}
      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@v4
      #   with:
      #     name: myDocker/repository
      #     username: ${{ steps.gcloud.outputs.username }}
      #     password: ${{ steps.gcloud.outputs.password }}
      #     registry: eu.gcr.io
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          cache: true
          cache-repository: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REPOSITORY }}/${{ env.PROJECT_NAME }}/cache
